# Generated by Django 4.1.7 on 2023-10-26 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('payments', '0005_temporaryguestmetadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1500)),
                ('image', models.CharField(max_length=100)),
                ('image_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('category', models.CharField(max_length=100)),
                ('organiser', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('location', models.CharField(max_length=100, null=True)),
                ('raw_name', models.CharField(max_length=100, null=True)),
                ('semantic_field', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_name', models.CharField(max_length=100)),
                ('adult_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('companion', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('base_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_name', models.CharField(max_length=100)),
                ('adult_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('companion', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('base_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
            ],
        ),
    ]
