# Generated by Django 4.1.7 on 2023-11-14 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_temporaryguestmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1500)),
                ('image', models.CharField(max_length=100)),
                ('image_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100, null=True)),
                ('raw_name', models.CharField(max_length=100, null=True)),
                ('organiser', models.CharField(max_length=100)),
                ('has_more_options', models.BooleanField(default=False)),
                ('options_common_city', models.BooleanField(default=False)),
                ('common_location', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=100, null=True)),
                ('semantic_field', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100, null=True)),
                ('county', models.CharField(default='', max_length=100, null=True)),
                ('iban', models.CharField(max_length=100, null=True)),
                ('extra_details', models.CharField(max_length=3000, null=True)),
                ('map_location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.maplocation')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('duration', models.DurationField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('location', models.CharField(default='', max_length=100, null=True)),
                ('rating', models.FloatField(default=0)),
                ('number_ratings', models.IntegerField(default=0)),
                ('details', models.CharField(max_length=3000, null=True)),
                ('city', models.CharField(default='', max_length=100, null=True)),
                ('county', models.CharField(default='', max_length=100, null=True)),
                ('map_location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.maplocation')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_name', models.CharField(max_length=100)),
                ('adult_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('companion', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('base_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('base_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceoption')),
            ],
        ),
    ]
