# Generated by Django 4.1.7 on 2023-07-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('rating', models.FloatField(default=0.0)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
