# Generated by Django 4.1.7 on 2023-11-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
