# Generated by Django 4.1.7 on 2023-07-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
