# Generated by Django 4.1.7 on 2023-11-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_category_remove_service_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='details',
            new_name='extra_details',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='common_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='iban',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='options_common_city',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='details',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AddField(
            model_name='service',
            name='map_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.maplocation'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='map_location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.maplocation'),
        ),
    ]
