# Generated by Django 4.1.7 on 2023-07-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_title_service_name_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='organiser',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
