# Generated by Django 4.1.7 on 2023-07-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_organiser_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_type',
            field=models.CharField(default='jpg', max_length=10),
            preserve_default=False,
        ),
    ]
