# Generated by Django 4.1.7 on 2023-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_maplocation_rename_details_service_extra_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceoption',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='county',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
