# Generated by Django 4.1.7 on 2023-07-08 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_service_image_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_name', models.CharField(max_length=100)),
                ('adult_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('insotitor', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('base_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senior_name', models.CharField(max_length=100)),
                ('adult_name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('companion', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('base_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
            ],
        ),
    ]
