# Generated by Django 4.1.7 on 2023-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceoption_city_serviceoption_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
