# Generated by Django 4.1.7 on 2023-11-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_serviceoption_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
