# Generated by Django 4.1.7 on 2023-07-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_purchasedservice_cartservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedservice',
            old_name='insotitor',
            new_name='companion',
        ),
    ]
