# Generated by Django 4.1.7 on 2023-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_rename_insotitor_purchasedservice_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='semantic_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
