# Generated by Django 4.1.7 on 2023-11-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceoption_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceoption',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
