# Generated by Django 4.0 on 2023-10-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_temporaryguestmetadata'),
        ('services', '0006_rename_insotitor_purchasedservice_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedservice',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
    ]
