# Generated by Django 4.1.7 on 2023-10-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_purchasedservice_payment'),
        ('services', '0007_service_semantic_field'),
    ]

    operations = [
    ]
