# Generated by Django 4.1.7 on 2023-11-12 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_serviceoption_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartservice',
            name='adult_name',
        ),
        migrations.RemoveField(
            model_name='cartservice',
            name='companion',
        ),
        migrations.RemoveField(
            model_name='cartservice',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartservice',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='cartservice',
            name='senior_name',
        ),
        migrations.AddField(
            model_name='cartservice',
            name='number_of_participants',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartservice',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.serviceoption'),
        ),
        migrations.AddField(
            model_name='cartservice',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
