name: Django CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]  # Specify Python 3.9 here

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2  # Use actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip  # Use python explicitly
        pip install -r silvercare/requirements.txt  # Use pip explicitly
    - name: Run Tests
      env:
          SILVERCARE_SECRET_KEY: ${{ secrets.SILVERCARE_SECRET_KEY }}
          SILVERCARE_DATABASE_NAME: ${{ secrets.SILVERCARE_DATABASE_NAME }}
          SILVERCARE_DATABASE_USER: ${{ secrets.SILVERCARE_DATABASE_USER }}
          SILVERCARE_DATABASE_PASSWORD: ${{ secrets.SILVERCARE_DATABASE_PASSWORD }}
          SILVERCARE_EMAIL_HOST: ${{ secrets.SILVERCARE_EMAIL_HOST }}
          SILVERCARE_EMAIL_HOST_USER: ${{ secrets.SILVERCARE_EMAIL_HOST_USER }}
          SILVERCARE_EMAIL_HOST_PASSWORD: ${{ secrets.SILVERCARE_EMAIL_HOST_PASSWORD }}
          SILVERCARE_EMAIL_PORT: ${{ secrets.SILVERCARE_EMAIL_PORT }}
          SILVERCARE_EMAIL_GMAIL_PASS: ${{ secrets.SILVERCARE_EMAIL_GMAIL_PASSWORD }}
          SILVERCARE_PATH_TO_FIMG: ${{ secrets.SILVERCARE_PATH_TO_FIMG }}
          SILVERCARE_BASE_URL: ${{ secrets.SILVERCARE_BASE_URL }}
          SILVERCARE_STRIPE_SECRET_KEY: ${{ secrets.SILVERCARE_STRIPE_SECRET_KEY }}
          SILVERCARE_STRIPE_PUBLIC_KEY: ${{ secrets.SILVERCARE_STRIPE_PUBLIC_KEY }}
          SILVERCARE_STRIPE_WEBHOOK_KEY: ${{ secrets.SILVERCARE_STRIPE_WEBHOOK_KEY }}
          SILVERCARE_PROD_STRIPE_PUBLIC_KEY: ${{ secrets.SILVERCARE_PROD_STRIPE_PUBLIC_KEY }}
          SILVERCARE_PROD_STRIPE_SECRET_KEY: ${{ secrets.SILVERCARE_PROD_STRIPE_SECRET_KEY }}
      run: |
        python silvercare/manage.py test  # Use python explicitly
