# Generated by Django 4.1.7 on 2023-09-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evt_id', models.CharField(max_length=255)),
                ('metadata', models.CharField(max_length=1000)),
            ],
        ),
    ]
