# Generated by Django 4.1.7 on 2023-09-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='evt_id',
            new_name='payment_intent_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='idempotency_request_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
