# Generated by Django 4.1.7 on 2023-09-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_evt_id_checkout_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout_email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
