# Generated by Django 4.1.7 on 2023-09-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_checkout_checkout_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryGuestMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.CharField(max_length=3000)),
            ],
        ),
    ]
